### ISSUE TITLE
After updating, it failed to load plugin

### ISSUE THREAD

**Issue by jakeoung** [JeppeKlitgaard/ObsidianAnkiBridge#14]
Sorry as I commit many issues :P I'm using the insider desktop version of Obsidian, but I couldn't install the plugin after upgrading it.

<img width="908" alt="image" src="https://user-images.githubusercontent.com/2376897/150655559-3ce3d108-fd18-4e3c-aabf-8f352c7a14a1.png">

## Sanity checks

- [v ] I am using the latest version of the plugin
- [v ] I am using the latest version of Obsidian
- [ v] I have read the README

## Diagnositics

| Component   | Version |
| ----------- | ------- |
| Obsidian    | ....... |
| AnkiBridge  | ....... |
| Anki        | ....... |
| AnkiConnect | ....... |

### Reproduce

- Steps to reproduce the behavior:

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by JeppeKlitgaard** [comment]
Whoops. This is definitely my bad. I changed something around in the build system. I can reproduce and will aim to fix this asap.

**Comment by JeppeKlitgaard** [comment]
This should be fixed in version `0.6.14`, which is now available.
