### ISSUE TITLE
Anki cards not showing the actual picture

### ISSUE THREAD

**Issue by jsjuris89** [JeppeKlitgaard/ObsidianAnkiBridge#2]
![Imgur](https://i.imgur.com/M5VQIJq.png)
This syntax gives me this:
![Imgur](https://i.imgur.com/FL4997p.png)

# Possible problem
Obsidian shows I have currently installed **0.2.21 version**. Should be latest version because I installed the plugin on 1st January via community plugins. [Imgur](https://i.imgur.com/SJXMsKK.png)
I tried pressing `Update` that didnt change anything.

Could it be possible that I dont have latest version installed and thats why image is not being rendered in Anki?

I have Windows 11.
Anki version is **⁨2.1.49**

**Comment by JeppeKlitgaard** [comment]
The latest version of AnkiBridge is `0.4.0`. Images are not supported in the version you are using.

Please update the plugin.

**Comment by jsjuris89** [comment]
I have 0.13.14 Obsidian. Should be fine.

Pressing update doesn't do anything it still says same "Version 0.4.0 (currently installed 0.2.21)". So how can I update?

**Comment by JeppeKlitgaard** [comment]
Only 0.13.16+ versions of Obsidian are supported. These are only available to Obsidian Insiders for now. You will have to wait until the next non-insider version is released or alternatively purchase Obsidian Insider access.
