### ISSUE TITLE
Youtube video rendering?

### ISSUE THREAD

**Issue by jsjuris89** [JeppeKlitgaard/ObsidianAnkiBridge#3]
Plugin version **0.4.0**
Obsidian **0.13.19**

Cannot render a youtube video in Anki.
`[video](youtube_url)` syntax doesn't work.

![Screenshot 2022-01-07 161018](https://user-images.githubusercontent.com/53792052/148555780-12df6192-a732-4434-9357-9d4d8e2ca479.png)

```md
#anki/start
some video?
#anki/---
[test](https://www.youtube.com/watch?v=l9nh1l8ZIJQ)
#anki/end
```

What kind of support this plugin has for videos?

**Comment by JeppeKlitgaard** [comment]
Hey Juris,

That's just a link in Obsidian, so it will be rendered as a link in Anki. This is expected and intended behaviour.

The video embedding works similar to the image and and audio embedding: it embeds a local file.
